##
## Helper docker compose file for doing local infogami dev. You probably want to run something like:
## docker compose -f compose.yml -f compose.override.yml -f compose.infogami-local.yml up -d
##

version: "3.8"
services:
  web:
    volumes:
      - ./vendor/infogami:/openlibrary/vendor/infogami
  covers:
    volumes:
      - ./vendor/infogami:/openlibrary/vendor/infogami
  infobase:
    volumes:
      - ./vendor/infogami:/openlibrary/vendor/infogami
  home:
    volumes:
      - ./vendor/infogami:/openlibrary/vendor/infogami
  solr-updater:
    volumes:
      - ./vendor/infogami:/openlibrary/vendor/infogami
